# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoEASIN
                                 A QGIS plugin
 Data downloader from EASIN Geospatial Web Service 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-26
        copyright            : (C) 2021 by Patricio Soriano. Geoinnova
        email                : patricio.soriano@geoinnova.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoEASIN class from file GeoEASIN.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_easin import GeoEASIN
    return GeoEASIN(iface)
